// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtuvelaqknujdfkohzuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dXZlbGFxa251amRma29oenVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTA0OTUsImV4cCI6MjA2NzY2NjQ5NX0.Npk3kY0uOf497VIUuPUWKDT_RhwuCS2Uqs9ZoQylXis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});